### ISSUE TITLE
[SETTING] Initial Settings

### ISSUE THREAD

**Issue by SeonJK** [euphony-io/order-with#1]
- Implement libraries
- [x] Euphony
- [x] Room
- [x] Glide
- Set build.gradle
- [x] DataBinding 
- Add permissions
- [x] RECORD_AUDIO
- Update .gitignore
- [x] .idea/vcs.xml
- [x] .idea/gradle.xml

**Comment by serim53** [comment]
Good! How about adding viewBinding in build.gradle?

**Comment by SeonJK** [comment]
you mean not DataBinding but ViewBinding?

**Comment by serim53** [comment]
> you mean not DataBinding but ViewBinding?

Nope! We can apply both at the same time!

**Comment by SeonJK** [comment]
Thanks for feedback! I applied it!!!

**Comment by SeonJK** [comment]
> > you mean not DataBinding but ViewBinding?
> 
> Nope! We can apply both at the same time!

As I know, DataBinding includes ViewBinding!

**Comment by SeonJK** [comment]
https://developer.android.com/topic/libraries/data-binding#:~:text=null%20pointer%20exceptions.-,Note,-%3A%20In%20many

In this link, only using binding to replace `findViewById()`, `viewBinding` would be simpler than `dataBinding`.

**Comment by serim53** [comment]
> 



> https://developer.android.com/topic/libraries/data-binding#:~:text=null%20pointer%20exceptions.-,Note,-%3A%20In%20many
> 
> In this link, only using binding to replace `findViewById()`, `viewBinding` would be simpler than `dataBinding`.

Oops... I've been writing both, but something must have gone wrong..! Oh, But Do we need a binding to make a compose app?

**Comment by phj0407** [comment]
Oh...I know the same content as Jun-seok said. So I've been worked  adding " id 'kotlin-android-extensions' " in build.gradle and not using findViewById(). 

Is it better changing my ways? and using findViewById() ?

**Comment by serim53** [comment]
> Oh...I know the same content as Jun-seok said. So I've been worked adding " id 'kotlin-android-extensions' " in build.gradle and not using findViewById().
> 
> Is it better changing my ways? and using findViewById() ?

Maybe the Kotlin Extension is deprecated, and the replacement for it is viewbinding! So if you put it in, it will work the same way as you used to. But I don't think view binding is necessary when using the compose app maybe..! I'll have to look for more!

**Comment by SeonJK** [comment]
For MVVM design pattern, I think binding is necessary!

Frankly, I need more study about why MVVM needs DataBinding

**Comment by SeonJK** [comment]
Then, I am not going to add dataBinding setting. After We need it, progress that time!
